const testData = [
    {
        "item_id": 196,
        "title": "собака",
        "owner_id": 53,
        "category_id": 24,
        "city_id": null,
        "price": "500.00",
        "size": "",
        "color": "",
        "condition": "",
        "year_of_manufacture": null,
        "created_at": "2024-07-07T13:06:20.917Z",
        "description": "",
        "city": "Хайфа"
    },
    {
        "item_id": 195,
        "title": "Кошка",
        "owner_id": 53,
        "category_id": 25,
        "city_id": null,
        "price": "90.00",
        "size": "",
        "color": "",
        "condition": "",
        "year_of_manufacture": null,
        "created_at": "2024-07-07T13:03:52.972Z",
        "description": "",
        "city": "Хайфа"
    },
    {
        "item_id": 137,
        "title": "Small cat",
        "owner_id": 52,
        "category_id": 22,
        "city_id": null,
        "price": "0.00",
        "size": "",
        "color": "",
        "condition": "",
        "year_of_manufacture": null,
        "created_at": "2024-02-19T05:25:26.778Z",
        "description": "A good cat, I will give it to good hands, my husband has an allergy, so we are looking for new owners.",
        "city": "Bersheva"
    },
    {
        "item_id": 136,
        "title": "Manirure",
        "owner_id": 52,
        "category_id": 33,
        "city_id": null,
        "price": "140.00",
        "size": "",
        "color": "",
        "condition": "",
        "year_of_manufacture": null,
        "created_at": "2024-02-19T05:16:07.166Z",
        "description": "Fast, high-quality manicure, large palette of colors, I come to your home, my number is 0533 698 567",
        "city": "Haifa"
    },
    {
        "item_id": 197,
        "title": "собака",
        "owner_id": 53,
        "category_id": 24,
        "city_id": null,
        "price": "500.00",
        "size": "",
        "color": "",
        "condition": "",
        "year_of_manufacture": null,
        "created_at": "2024-07-07T13:06:20.917Z",
        "description": "",
        "city": "Хайфа"
    },
    {
        "item_id": 198,
        "title": "Кошка",
        "owner_id": 53,
        "category_id": 25,
        "city_id": null,
        "price": "90.00",
        "size": "",
        "color": "",
        "condition": "",
        "year_of_manufacture": null,
        "created_at": "2024-07-07T13:03:52.972Z",
        "description": "",
        "city": "Хайфа"
    },
    {
        "item_id": 199,
        "title": "Small cat",
        "owner_id": 52,
        "category_id": 22,
        "city_id": null,
        "price": "0.00",
        "size": "",
        "color": "",
        "condition": "",
        "year_of_manufacture": null,
        "created_at": "2024-02-19T05:25:26.778Z",
        "description": "A good cat, I will give it to good hands, my husband has an allergy, so we are looking for new owners.",
        "city": "Bersheva"
    },
    {
        "item_id": 200,
        "title": "Manirure",
        "owner_id": 52,
        "category_id": 33,
        "city_id": null,
        "price": "140.00",
        "size": "",
        "color": "",
        "condition": "",
        "year_of_manufacture": null,
        "created_at": "2024-02-19T05:16:07.166Z",
        "description": "Fast, high-quality manicure, large palette of colors, I come to your home, my number is 0533 698 567",
        "city": "Haifa"
    }
]

export default testData