export const cities = [
    { rus: "Акко", en: "Akko", he: "עכו" },
    { rus: "Арад", en: "Arad", he: "ערד" },
    { rus: "Ашдод", en: "Ashdod", he: "אשדוד" },
    { rus: "Ашкелон", en: "Ashkelon", he: "אשקלון" },
    { rus: "Бар-Яхим", en: "Bar-Yahim", he: "בר-יחים" },
    { rus: "Беэр-Шева", en: "Beersheba", he: "באר שבע" },
    { rus: "Бейт-Шемеш", en: "Beit Shemesh", he: "בית שמש" },
    { rus: "Гальим", en: "Galim", he: "גלים" },
    { rus: "Ган-Явне", en: "Gan Yavne", he: "גן יבנה" },
    { rus: "Гат-Тавор", en: "Gat-Tavor", he: "גת תבור" },
    { rus: "Герцлия", en: "Herzliya", he: "הרצליה" },
    { rus: "Гиватаим", en: "Givataim", he: "גבעתיים" },
    { rus: "Гиват-Зев", en: "Givat Zev", he: "גבעת זאב" },
    { rus: "Гиват-Шмуэль", en: "Givat Shmuel", he: "גבעת שמואל" },
    { rus: "Димона", en: "Dimona", he: "דימונה" },
    { rus: "Эйлат", en: "Eilat", he: "אילת" },
    { rus: "Иерусалим", en: "Jerusalem", he: "ירושלים" },
    { rus: "Кафр-Бирим", en: "Kafr Birim", he: "כפר בירים" },
    { rus: "Кфар-Кана", en: "Kfar Qana", he: "כפר קנא" },
    { rus: "Кесария", en: "Caesarea", he: "קיסריה" },
    { rus: "Кирьят-Арба", en: "Kiryat Arba", he: "קריית ארבע" },
    { rus: "Кирьят-Бялик", en: "Kiryat Bialik", he: "קריית ביאליק" },
    { rus: "Кирьят-Гат", en: "Kiryat Gat", he: "קריית גת" },
    { rus: "Кирьят-Хаим", en: "Kiryat Haim", he: "קריית חיים" },
    { rus: "Кирьят-Малхи", en: "Kiryat Malakhi", he: "קריית מלאכי" },
    { rus: "Кирьят-Маца", en: "Kiryat Matsa", he: "קריית מצא" },
    { rus: "Кирьят-Моцкин", en: "Kiryat Motzkin", he: "קריית מוצקין" },
    { rus: "Кирьят-Оно", en: "Kiryat Ono", he: "קריית אונו" },
    { rus: "Кирьят-Шмона", en: "Kiryat Shmona", he: "קריית שמונה" },
    { rus: "Кирьят-Ям", en: "Kiryat Yam", he: "קריית ים" },
    { rus: "Кирьят-Цви", en: "Kiryat Zvi", he: "קריית צבי" },
    { rus: "Кармиэль", en: "Carmiel", he: "כרמיאל" },
    { rus: "Кфар-Сава", en: "Kfar Saba", he: "כפר סבא" },
    { rus: "Лахиш", en: "Lachish", he: "לחיש" },
    { rus: "Лод", en: "Lod", he: "לוד" },
    { rus: "Маанит", en: "Maanit", he: "מענית" },
    { rus: "Маале-Адумим", en: "Maale Adumim", he: "מעלה אדומים" },
    { rus: "Мигдаль-ха-Эмек", en: "Migdal HaEmek", he: "מגדל העמק" },
    { rus: "Модиин", en: "Modiin", he: "מודיעין" },
    { rus: "Нагария", en: "Nahariya", he: "נהריה" },
    { rus: "Нетания", en: "Netanya", he: "נתניה" },
    { rus: "Нешер", en: "Nesher", he: "נשר" },
    { rus: "Петах-Тиква", en: "Petah Tikva", he: "פתח תקווה" },
    { rus: "Рамат-Ган", en: "Ramat Gan", he: "רמת גן" },
    { rus: "Рамат-Шарон", en: "Ramat Hasharon", he: "רמת השרון" },
    { rus: "Рамле", en: "Ramle", he: "רמלה" },
    { rus: "Реховот", en: "Rehovot", he: "רחובות" },
    { rus: "Ришон-ле-Цион", en: "Rishon Lezion", he: "ראשון לציון" },
    { rus: "Рош-ха-Аин", en: "Rosh HaAyin", he: "ראש העין" },
    { rus: "Сделана", en: "Sde Lana", he: "סד לנה" },
    { rus: "Тверия", en: "Tiberias", he: "טבריה" },
    { rus: "Тель-Авив", en: "Tel Aviv", he: "תל אביב" },
    { rus: "Тель-Ягд", en: "Tel Yagid", he: "תל יגיד" },
    { rus: "Тира", en: "Tira", he: "טירה" },
    { rus: "Умм-эль-Фахм", en: "Umm el-Fahm", he: "אום אל-פחם" },
    { rus: "Цфат", en: "Safed", he: "צפת" },
    { rus: "Цфараим", en: "Tsfaraim", he: "צפרים" },
    { rus: "Хадера", en: "Hadera", he: "חדרה" },
    { rus: "Хайфа", en: "Haifa", he: "חיפה" },
    { rus: "Шарона", en: "Sharona", he: "שרונה" },
    { rus: "Шаар-ха-Галиль", en: "Shaar HaGalil", he: "שער הגליל" },
    { rus: "Шдерот", en: "Sderot", he: "שדרות" },
    { rus: "Эмек-Ярден", en: "Emek Yarden", he: "עמק הירדן" }
  ];