
export const cities = 
    {
        rus: [
            "Акко",
            "Арад",
            "Ашдод",
            "Ашкелон",
            "Бар-Яхим",
            "Беэр-Шева",
            "Бейт-Шемеш",
            "Гальим",
            "Ган-Явне",
            "Гат-Тавор",
            "Герцлия",
            "Гиватаим",
            "Гиват-Зев",
            "Гиват-Шмуэль",
            "Димона",
            "Эйлат",
            "Иерусалим",
            "Кафр-Бирим",
            "Кфар-Кана",
            "Кесария",
            "Кирьят-Арба",
            "Кирьят-Бялик",
            "Кирьят-Гат",
            "Кирьят-Хаим",
            "Кирьят-Малхи",
            "Кирьят-Маца",
            "Кирьят-Моцкин",
            "Кирьят-Оно",
            "Кирьят-Шмона",
            "Кирьят-Ям",
            "Кирьят-Цви",
            "Кармиэль",
            "Кфар-Сава",
            "Лахиш",
            "Лод",
            "Маанит",
            "Маале-Адумим",
            "Мигдаль-ха-Эмек",
            "Модиин",
            "Нагария",
            "Нетания",
            "Нешер",
            "Петах-Тиква",
            "Рамат-Ган",
            "Рамат-Шарон",
            "Рамле",
            "Реховот",
            "Ришон-ле-Цион",
            "Рош-ха-Аин",
            "Сделана",
            "Тверия",
            "Тель-Авив",
            "Тель-Ягд",
            "Тира",
            "Умм-эль-Фахм",
            "Цфат",
            "Цфараим",
            "Хадера",
            "Хайфа",
            "Шарона",
            "Шаар-ха-Галиль",
            "Шдерот",
            "Эмек-Ярден"
          ],
          
          en: [
            "Akko",
            "Arad",
            "Ashdod",
            "Ashkelon",
            "Bar-Yahim",
            "Beersheba",
            "Beit Shemesh",
            "Galim",
            "Gan Yavne",
            "Gat-Tavor",
            "Herzliya",
            "Givataim",
            "Givat Zev",
            "Givat Shmuel",
            "Dimona",
            "Eilat",
            "Jerusalem",
            "Kafr Birim",
            "Kfar Qana",
            "Caesarea",
            "Kiryat Arba",
            "Kiryat Bialik",
            "Kiryat Gat",
            "Kiryat Haim",
            "Kiryat Malakhi",
            "Kiryat Motzkin",
            "Kiryat Matsa",
            "Kiryat Ono",
            "Kiryat Shmona",
            "Kiryat Yam",
            "Kiryat Zvi",
            "Carmiel",
            "Kfar Saba",
            "Lachish",
            "Lod",
            "Maanit",
            "Maale Adumim",
            "Migdal HaEmek",
            "Modiin",
            "Nahariya",
            "Netanya",
            "Nesher",
            "Petah Tikva",
            "Ramat Gan",
            "Ramat Hasharon",
            "Ramle",
            "Rehovot",
            "Rishon Lezion",
            "Rosh HaAyin",
            "Sde Lana",
            "Tiberias",
            "Tel Aviv",
            "Tel Yagid",
            "Tira",
            "Umm el-Fahm",
            "Safed",
            "Tsfaraim",
            "Hadera",
            "Haifa",
            "Sharona",
            "Shaar HaGalil",
            "Sderot",
            "Emek Yarden"
          ]
          
    }
;